# Candace Savonen Aug 2021
# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  - files:
      - source: .github/workflows/
        dest: .github/workflows/
        deleteOrphaned: true
        exclude: |
          send-updates.yml
          test-send-updates.yml
          starting-course.yml
          release-notes.yml
          docker-test.yml
          docker-build.yml
      - source: scripts/
        dest: scripts/
        deleteOrphaned: true
      - source: .github/ISSUE_TEMPLATE/course-problem-report.md
        dest: .github/ISSUE_TEMPLATE/course-problem-report.md
      - source: .github/ISSUE_TEMPLATE/course-content-add.md
        dest: .github/ISSUE_TEMPLATE/course-content-add.md
      - source: style-sets
        dest: style-sets
      - source: assets/box_images/
        dest: assets/box_images/
  # Repositories to receive changes
    repos: |
      jhudsl/Documentation_and_Usability
      jhudsl/Informatics_Research_Leadership
      jhudsl/Data_Management_for_Cancer_Research
      jhudsl/Computing_for_Cancer_Informatics
      jhudsl/Adv_Reproducibility_in_Cancer_Informatics
      jhudsl/Reproducibility_in_Cancer_Informatics
      jhudsl/Dissemination_and_Engagement
      jhudsl/Cancer_Clinical_Informatics
      jhudsl/Machine_Learning_for_Cancer_Informatics
      jhudsl/Cancer_Informatics_Data_Visualization
      jhudsl/Cancer_Genome_Informatics
      jhudsl/Cancer-Imaging-Informatics
      datatrail-jhu/DataTrail_Template
      abyzovlab/CNVpytor-course
      opencasestudies/OCS_Guide
      tmm211/dsp-terra-mooc-test2
      fhdsl/Choosing_Genomics_Tools
      fhdsl/NIH_Data_Sharing
      fhdsl/FH_Cluster_Guide
###ADD NEW REPO HERE following the format above#

### These are custom groups for syncing -- not all files needs to be synced
  - files:
    - source: config_automation.yml
      dest: config_automation.yml
    - source: .github/workflows/pull-request.yml
      dest: .github/workflows/pull-request.yml
    repos: |
      jhudsl/OTTR_Template_Website

  - files:
    - source: config_automation.yml
      dest: config_automation.yml
    - source: .github/workflows/delete-preview.yml
      dest: .github/workflows/delete-preview.yml
    - source: .github/workflows/send-updates.yml
      dest: .github/workflows/send-updates.yml
    - source: .github/workflows/test-send-updates.yml
      dest: .github/workflows/test-send-updates.yml
    - source: scripts/make_screenshots.R
      dest: scripts/make_screenshots.R
    - source: scripts/switch_sync_repo.R
      dest: scripts/switch_sync_repo.R
    repos: |
      jhudsl/OTTR_Quizzes

  - files:
    - source: .github/workflows/
      dest: .github/workflows/
      exclude: |
        starting-course.yml
        release-notes.yml
    - source: .github/switch_sync_repo.R
      dest: .github/switch_sync_repo.R
    - source: .github/ISSUE_TEMPLATE/course-problem-report.md
      dest: .github/ISSUE_TEMPLATE/course-problem-report.md
    - source: .github/ISSUE_TEMPLATE/course-content-add.md
      dest: .github/ISSUE_TEMPLATE/course-content-add.md
    - source: scripts/make_screenshots.R
      dest: scripts/make_screenshots.R
    - source: scripts/git_repo_check.R
      dest: scripts/git_repo_check.R
    - source: code_of_conduct.md
      dest: code_of_conduct.md
    - source: assets/box_images/
      dest: assets/box_images/
    - source: assets/style.css
      dest: assets/AnVIL_style/style.css
    repos: |
      jhudsl/AnVIL_Template
