# Candace Savonen Aug 2021

name: Sync Files

on:
  release:
    types:
    - published
  workflow_dispatch:
    inputs:
      prtag:
        description: 'Tag to use?'
        required: true
        default: 'null'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Login as jhudsl-robot
        run: |
          git config --local user.email "itcrtrainingnetwork@gmail.com"
          git config --local user.name "jhudsl-robot"

      - name: Get the version
        id: get_tag
        run: |
          if [ github.event.inputs.prtag == 'null' ]
          then
            echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)
          fi
          if [ github.event.inputs.prtag != 'null' ]
          then
            echo ::set-output name=version::${{ github.event.inputs.prtag }}
          fi

      - name: Run Mechanics File Sync
        uses: BetaHuhn/repo-file-sync-action@v1.17.21
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          COMMIT_BODY: release-${{ steps.get_tag.outputs.version }}
